permalink: /blog/:title.html
exclude:
  - Rakefile
  - Gemfile
  - .gitignore
author: zuozuo
email: zzhattzzh@126.com  
web: zuozuo.github.io
twitter: zuozuo
github: zuozuo
pygments: true
markdown: redcarpet
